# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version = 0.8.0
maven_group = rocks.blackblock
archives_base_name = screenbuilder

# Dependencies
fabric_version=0.135.0+1.21.10
blackblock_bib_version=0.5.0
polymc_version=5.7.0+1.21.10
chunker_version=0.8.0
